# Generated by Django 2.1.7 on 2020-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190408_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(choices=[('Select your city', 'Select your city'), ('Mangalore', 'Mangalore'), ('Surathkal', 'Surathkal'), ('Udupi', 'Udupi'), ('Manipal', 'Manipal')], default='Surathkal', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_size',
            field=models.CharField(choices=[('Select vehicle size', 'Select vehicle size'), ('Personal vehicle', 'Personal vehicle'), ('Commercial vehicle', 'Commercial vehicle'), ('Sport utility vehicle', 'Sport utility vehicle'), ('Special purpose vehicle', 'Special purpose vehicle')], default='Personal vehicle', max_length=30),
        ),
    ]
